/*
 * Copyright (C) Joan Bruguera 2010
 *
 * This file is part of CalcBatx.
 *
 * CalcBatx is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * CalcBatx is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License
 * along with CalcBatx.  If not, see <http://www.gnu.org/licenses/>.
 */

package calcbatx;

import org.jdesktop.application.SingleFrameApplication;
import org.jdesktop.application.Action;
import org.jdesktop.application.FrameView;
import javax.swing.DefaultListModel;
import javax.swing.JDialog;
import javax.swing.JFrame;
import java.awt.Color;
import java.awt.Point;
import java.awt.event.MouseEvent;
import java.awt.event.MouseWheelEvent;
import java.awt.event.KeyEvent;
import java.util.Arrays;

/**
 * The application's main frame.
 */
public class CalcBatxView extends FrameView {

    public CalcBatxView(SingleFrameApplication app) {
        super(app);

        initComponents();
    }
    
    @Action
    public void showAboutBox() {
        if (aboutBox == null) {
            JFrame mainFrame = CalcBatxApp.getApplication().getMainFrame();
            aboutBox = new CalcBatxAboutBox(mainFrame);
            aboutBox.setLocationRelativeTo(mainFrame);
        }
        CalcBatxApp.getApplication().show(aboutBox);
    }
    
    private JDialog aboutBox = null;

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        panelPrincipal = new javax.swing.JPanel();
        textEntrada = new javax.swing.JTextField();
        textResultat = new javax.swing.JTextField();
        labelFx = new javax.swing.JLabel();
        jSplitPane1 = new javax.swing.JSplitPane();
        panelPestanyes = new javax.swing.JTabbedPane();
        panelTeclat = new javax.swing.JPanel();
        panelTeclatControlValors = new javax.swing.JPanel();
        panelTeclatControl = new javax.swing.JPanel();
        botoRetroces = new javax.swing.JButton();
        botoReinicia = new javax.swing.JButton();
        panelTeclatValors = new javax.swing.JPanel();
        botoValorX = new javax.swing.JButton();
        botoValorI = new javax.swing.JButton();
        panelTeclatParentesisDerivada = new javax.swing.JPanel();
        panelTeclatParentesis = new javax.swing.JPanel();
        botoObrirParentesis = new javax.swing.JButton();
        botoTancarParentesis = new javax.swing.JButton();
        panelTeclatDerivada = new javax.swing.JPanel();
        botoDerivada = new javax.swing.JButton();
        panelTeclatNombres = new javax.swing.JPanel();
        botoNombre7 = new javax.swing.JButton();
        botoNombre8 = new javax.swing.JButton();
        botoNombre9 = new javax.swing.JButton();
        botoNombre4 = new javax.swing.JButton();
        botoNombre5 = new javax.swing.JButton();
        botoNombre6 = new javax.swing.JButton();
        botoNombre1 = new javax.swing.JButton();
        botoNombre2 = new javax.swing.JButton();
        botoNombre3 = new javax.swing.JButton();
        botoNombre0 = new javax.swing.JButton();
        botoPunt = new javax.swing.JButton();
        botoExp = new javax.swing.JButton();
        panelTeclatOperacions = new javax.swing.JPanel();
        botoElevar = new javax.swing.JButton();
        botoDividir = new javax.swing.JButton();
        botoMultiplicar = new javax.swing.JButton();
        botoRestar = new javax.swing.JButton();
        botoSumar = new javax.swing.JButton();
        panelGrafic = new calcbatx.GraficFuncio();
        panelPolinomi = new javax.swing.JPanel();
        botoProcessarPolinomi = new javax.swing.JButton();
        labelCoeficients = new javax.swing.JLabel();
        textCoeficients = new javax.swing.JTextField();
        labelArrels = new javax.swing.JLabel();
        textArrels = new javax.swing.JTextField();
        labelDerivada = new javax.swing.JLabel();
        labelPrimitiva = new javax.swing.JLabel();
        textDerivada = new javax.swing.JTextField();
        textPrimitiva = new javax.swing.JTextField();
        botoPujarDerivada = new javax.swing.JButton();
        botoPujarPrimitiva = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        labelExtrem1 = new javax.swing.JLabel();
        labelExtrem2 = new javax.swing.JLabel();
        labelNombreDivisions = new javax.swing.JLabel();
        textExtrem1 = new javax.swing.JTextField();
        textExtrem2 = new javax.swing.JTextField();
        textNombreParts = new javax.swing.JTextField();
        botoIntegrar = new javax.swing.JButton();
        labelIntegral = new javax.swing.JLabel();
        textIntegral = new javax.swing.JTextField();
        panelFuncions = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        llistaFuncionsUsuari = new javax.swing.JList();
        textFuncioUsuari = new javax.swing.JTextField();
        panelAfegirEsborrarFuncio = new javax.swing.JPanel();
        botoAfegirFuncioUsuari = new javax.swing.JButton();
        botoEsborrarFuncioUsuari = new javax.swing.JButton();
        labelFzero = new javax.swing.JLabel();
        labelValorX = new javax.swing.JLabel();
        textValorX = new javax.swing.JTextField();
        barraMenu = new javax.swing.JMenuBar();
        javax.swing.JMenu menuFitxer = new javax.swing.JMenu();
        javax.swing.JMenuItem tancarMenuItem = new javax.swing.JMenuItem();
        javax.swing.JMenu menuAjuda = new javax.swing.JMenu();
        ajudaMenuItem = new javax.swing.JMenuItem();
        barraEstat = new javax.swing.JPanel();
        javax.swing.JSeparator statusPanelSeparator = new javax.swing.JSeparator();
        labelEstat = new javax.swing.JLabel();
        menuGrafic = new javax.swing.JPopupMenu();
        menuMostrarRe = new javax.swing.JCheckBoxMenuItem();
        menuMostrarIm = new javax.swing.JCheckBoxMenuItem();

        panelPrincipal.setName("panelPrincipal"); // NOI18N

        textEntrada.getDocument().addDocumentListener(new javax.swing.event.DocumentListener(){
            public void changedUpdate(javax.swing.event.DocumentEvent e){processarEntrada();}
            public void removeUpdate(javax.swing.event.DocumentEvent e){processarEntrada();}
            public void insertUpdate(javax.swing.event.DocumentEvent e){processarEntrada();}
        });
        textEntrada.setFont(textEntrada.getFont().deriveFont((float)18));
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(calcbatx.CalcBatxApp.class).getContext().getResourceMap(CalcBatxView.class);
        textEntrada.setText(resourceMap.getString("textEntrada.text")); // NOI18N
        textEntrada.setName("textEntrada"); // NOI18N
        textEntrada.setPreferredSize(new java.awt.Dimension(6, 25));
        textEntrada.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textEntradaFocusGained(evt);
            }
        });

        textResultat.setEditable(false);
        textResultat.setFont(textResultat.getFont().deriveFont((float)18));
        textResultat.setText(resourceMap.getString("textResultat.text")); // NOI18N
        textResultat.setName("textResultat"); // NOI18N

        labelFx.setFont(resourceMap.getFont("labelFx.font")); // NOI18N
        labelFx.setText(resourceMap.getString("labelFx.text")); // NOI18N
        labelFx.setName("labelFx"); // NOI18N

        jSplitPane1.setName("jSplitPane1"); // NOI18N

        panelPestanyes.setName("panelPestanyes"); // NOI18N

        panelTeclat.setName("panelTeclat"); // NOI18N
        panelTeclat.setLayout(new java.awt.GridLayout(2, 2, 5, 5));

        panelTeclatControlValors.setName("panelTeclatControlValors"); // NOI18N
        panelTeclatControlValors.setLayout(new java.awt.GridLayout(2, 1));

        panelTeclatControl.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("panelTeclatControl.border.title"))); // NOI18N
        panelTeclatControl.setName("panelTeclatControl"); // NOI18N
        panelTeclatControl.setLayout(new java.awt.GridLayout(1, 0));

        botoRetroces.setText(resourceMap.getString("botoRetroces.text")); // NOI18N
        botoRetroces.setName("botoRetroces"); // NOI18N
        botoRetroces.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoRetrocesActionPerformed(evt);
            }
        });
        panelTeclatControl.add(botoRetroces);

        botoReinicia.setText(resourceMap.getString("botoReinicia.text")); // NOI18N
        botoReinicia.setName("botoReinicia"); // NOI18N
        botoReinicia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoReiniciaActionPerformed(evt);
            }
        });
        panelTeclatControl.add(botoReinicia);

        panelTeclatControlValors.add(panelTeclatControl);

        panelTeclatValors.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("panelTeclatValors.border.title"))); // NOI18N
        panelTeclatValors.setName("panelTeclatValors"); // NOI18N
        panelTeclatValors.setLayout(new java.awt.GridLayout(1, 0));

        botoValorX.setText(resourceMap.getString("botoValorX.text")); // NOI18N
        botoValorX.setName("botoValorX"); // NOI18N
        botoValorX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoValorXActionPerformed(evt);
            }
        });
        panelTeclatValors.add(botoValorX);

        botoValorI.setText(resourceMap.getString("botoValorI.text")); // NOI18N
        botoValorI.setName("botoValorI"); // NOI18N
        botoValorI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoValorIActionPerformed(evt);
            }
        });
        panelTeclatValors.add(botoValorI);

        panelTeclatControlValors.add(panelTeclatValors);

        panelTeclat.add(panelTeclatControlValors);

        panelTeclatParentesisDerivada.setName("panelTeclatParentesisDerivada"); // NOI18N
        panelTeclatParentesisDerivada.setLayout(new java.awt.GridLayout(2, 1));

        panelTeclatParentesis.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("panelTeclatParentesis.border.title"))); // NOI18N
        panelTeclatParentesis.setName("panelTeclatParentesis"); // NOI18N
        panelTeclatParentesis.setLayout(new java.awt.GridLayout(1, 0));

        botoObrirParentesis.setText(resourceMap.getString("botoObrirParentesis.text")); // NOI18N
        botoObrirParentesis.setName("botoObrirParentesis"); // NOI18N
        botoObrirParentesis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoObrirParentesisActionPerformed(evt);
            }
        });
        panelTeclatParentesis.add(botoObrirParentesis);

        botoTancarParentesis.setText(resourceMap.getString("botoTancarParentesis.text")); // NOI18N
        botoTancarParentesis.setName("botoTancarParentesis"); // NOI18N
        botoTancarParentesis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoTancarParentesisActionPerformed(evt);
            }
        });
        panelTeclatParentesis.add(botoTancarParentesis);

        panelTeclatParentesisDerivada.add(panelTeclatParentesis);

        panelTeclatDerivada.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("panelTeclatDerivada.border.title"))); // NOI18N
        panelTeclatDerivada.setName("panelTeclatDerivada"); // NOI18N
        panelTeclatDerivada.setLayout(new java.awt.GridLayout(1, 0));

        botoDerivada.setText(resourceMap.getString("botoDerivada.text")); // NOI18N
        botoDerivada.setName("botoDerivada"); // NOI18N
        botoDerivada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoDerivadaActionPerformed(evt);
            }
        });
        panelTeclatDerivada.add(botoDerivada);

        panelTeclatParentesisDerivada.add(panelTeclatDerivada);

        panelTeclat.add(panelTeclatParentesisDerivada);

        panelTeclatNombres.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("panelTeclatNombres.border.title"))); // NOI18N
        panelTeclatNombres.setName("panelTeclatNombres"); // NOI18N
        panelTeclatNombres.setLayout(new java.awt.GridLayout(4, 4));

        botoNombre7.setText(resourceMap.getString("botoNombre7.text")); // NOI18N
        botoNombre7.setName("botoNombre7"); // NOI18N
        botoNombre7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoNombre7ActionPerformed(evt);
            }
        });
        panelTeclatNombres.add(botoNombre7);

        botoNombre8.setText(resourceMap.getString("botoNombre8.text")); // NOI18N
        botoNombre8.setName("botoNombre8"); // NOI18N
        botoNombre8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoNombre8ActionPerformed(evt);
            }
        });
        panelTeclatNombres.add(botoNombre8);

        botoNombre9.setText(resourceMap.getString("botoNombre9.text")); // NOI18N
        botoNombre9.setName("botoNombre9"); // NOI18N
        botoNombre9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoNombre9ActionPerformed(evt);
            }
        });
        panelTeclatNombres.add(botoNombre9);

        botoNombre4.setText(resourceMap.getString("botoNombre4.text")); // NOI18N
        botoNombre4.setName("botoNombre4"); // NOI18N
        botoNombre4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoNombre4ActionPerformed(evt);
            }
        });
        panelTeclatNombres.add(botoNombre4);

        botoNombre5.setText(resourceMap.getString("botoNombre5.text")); // NOI18N
        botoNombre5.setName("botoNombre5"); // NOI18N
        botoNombre5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoNombre5ActionPerformed(evt);
            }
        });
        panelTeclatNombres.add(botoNombre5);

        botoNombre6.setText(resourceMap.getString("botoNombre6.text")); // NOI18N
        botoNombre6.setName("botoNombre6"); // NOI18N
        botoNombre6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoNombre6ActionPerformed(evt);
            }
        });
        panelTeclatNombres.add(botoNombre6);

        botoNombre1.setText(resourceMap.getString("botoNombre1.text")); // NOI18N
        botoNombre1.setName("botoNombre1"); // NOI18N
        botoNombre1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoNombre1ActionPerformed(evt);
            }
        });
        panelTeclatNombres.add(botoNombre1);

        botoNombre2.setText(resourceMap.getString("botoNombre2.text")); // NOI18N
        botoNombre2.setName("botoNombre2"); // NOI18N
        botoNombre2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoNombre2ActionPerformed(evt);
            }
        });
        panelTeclatNombres.add(botoNombre2);

        botoNombre3.setText(resourceMap.getString("botoNombre3.text")); // NOI18N
        botoNombre3.setName("botoNombre3"); // NOI18N
        botoNombre3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoNombre3ActionPerformed(evt);
            }
        });
        panelTeclatNombres.add(botoNombre3);

        botoNombre0.setText(resourceMap.getString("botoNombre0.text")); // NOI18N
        botoNombre0.setName("botoNombre0"); // NOI18N
        botoNombre0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoNombre0ActionPerformed(evt);
            }
        });
        panelTeclatNombres.add(botoNombre0);

        botoPunt.setText(resourceMap.getString("botoPunt.text")); // NOI18N
        botoPunt.setName("botoPunt"); // NOI18N
        botoPunt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoPuntActionPerformed(evt);
            }
        });
        panelTeclatNombres.add(botoPunt);

        botoExp.setText(resourceMap.getString("botoExp.text")); // NOI18N
        botoExp.setName("botoExp"); // NOI18N
        botoExp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoExpActionPerformed(evt);
            }
        });
        panelTeclatNombres.add(botoExp);

        panelTeclat.add(panelTeclatNombres);

        panelTeclatOperacions.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("panelTeclatOperacions.border.title"))); // NOI18N
        panelTeclatOperacions.setName("panelTeclatOperacions"); // NOI18N
        panelTeclatOperacions.setLayout(new java.awt.GridLayout(5, 1));

        botoElevar.setText(resourceMap.getString("botoElevar.text")); // NOI18N
        botoElevar.setName("botoElevar"); // NOI18N
        botoElevar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoElevarActionPerformed(evt);
            }
        });
        panelTeclatOperacions.add(botoElevar);

        botoDividir.setText(resourceMap.getString("botoDividir.text")); // NOI18N
        botoDividir.setName("botoDividir"); // NOI18N
        botoDividir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoDividirActionPerformed(evt);
            }
        });
        panelTeclatOperacions.add(botoDividir);

        botoMultiplicar.setText(resourceMap.getString("botoMultiplicar.text")); // NOI18N
        botoMultiplicar.setName("botoMultiplicar"); // NOI18N
        botoMultiplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoMultiplicarActionPerformed(evt);
            }
        });
        panelTeclatOperacions.add(botoMultiplicar);

        botoRestar.setText(resourceMap.getString("botoRestar.text")); // NOI18N
        botoRestar.setName("botoRestar"); // NOI18N
        botoRestar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoRestarActionPerformed(evt);
            }
        });
        panelTeclatOperacions.add(botoRestar);

        botoSumar.setText(resourceMap.getString("botoSumar.text")); // NOI18N
        botoSumar.setName("botoSumar"); // NOI18N
        botoSumar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoSumarActionPerformed(evt);
            }
        });
        panelTeclatOperacions.add(botoSumar);

        panelTeclat.add(panelTeclatOperacions);

        panelPestanyes.addTab(resourceMap.getString("panelTeclat.TabConstraints.tabTitle"), panelTeclat); // NOI18N

        panelGrafic.setName("panelGrafic"); // NOI18N

        javax.swing.GroupLayout panelGraficLayout = new javax.swing.GroupLayout(panelGrafic);
        panelGrafic.setLayout(panelGraficLayout);
        panelGraficLayout.setHorizontalGroup(
            panelGraficLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
        );
        panelGraficLayout.setVerticalGroup(
            panelGraficLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 370, Short.MAX_VALUE)
        );

        panelPestanyes.addTab(resourceMap.getString("panelGrafic.TabConstraints.tabTitle"), panelGrafic); // NOI18N

        panelPolinomi.setName("panelPolinomi"); // NOI18N

        botoProcessarPolinomi.setText(resourceMap.getString("botoProcessarPolinomi.text")); // NOI18N
        botoProcessarPolinomi.setName("botoProcessarPolinomi"); // NOI18N
        botoProcessarPolinomi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoProcessarPolinomiActionPerformed(evt);
            }
        });

        labelCoeficients.setText(resourceMap.getString("labelCoeficients.text")); // NOI18N
        labelCoeficients.setName("labelCoeficients"); // NOI18N

        textCoeficients.setEditable(false);
        textCoeficients.setText(resourceMap.getString("textCoeficients.text")); // NOI18N
        textCoeficients.setName("textCoeficients"); // NOI18N

        labelArrels.setText(resourceMap.getString("labelArrels.text")); // NOI18N
        labelArrels.setName("labelArrels"); // NOI18N

        textArrels.setEditable(false);
        textArrels.setText(resourceMap.getString("textArrels.text")); // NOI18N
        textArrels.setName("textArrels"); // NOI18N

        labelDerivada.setText(resourceMap.getString("labelDerivada.text")); // NOI18N
        labelDerivada.setName("labelDerivada"); // NOI18N

        labelPrimitiva.setText(resourceMap.getString("labelPrimitiva.text")); // NOI18N
        labelPrimitiva.setName("labelPrimitiva"); // NOI18N

        textDerivada.setEditable(false);
        textDerivada.setText(resourceMap.getString("textDerivada.text")); // NOI18N
        textDerivada.setName("textDerivada"); // NOI18N

        textPrimitiva.setEditable(false);
        textPrimitiva.setText(resourceMap.getString("textPrimitiva.text")); // NOI18N
        textPrimitiva.setName("textPrimitiva"); // NOI18N

        botoPujarDerivada.setText(resourceMap.getString("botoPujarDerivada.text")); // NOI18N
        botoPujarDerivada.setName("botoPujarDerivada"); // NOI18N
        botoPujarDerivada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoPujarDerivadaActionPerformed(evt);
            }
        });

        botoPujarPrimitiva.setText(resourceMap.getString("botoPujarPrimitiva.text")); // NOI18N
        botoPujarPrimitiva.setName("botoPujarPrimitiva"); // NOI18N
        botoPujarPrimitiva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoPujarPrimitivaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPolinomiLayout = new javax.swing.GroupLayout(panelPolinomi);
        panelPolinomi.setLayout(panelPolinomiLayout);
        panelPolinomiLayout.setHorizontalGroup(
            panelPolinomiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPolinomiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPolinomiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPolinomiLayout.createSequentialGroup()
                        .addGroup(panelPolinomiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelArrels)
                            .addComponent(labelCoeficients)
                            .addComponent(labelDerivada)
                            .addComponent(labelPrimitiva))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelPolinomiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPolinomiLayout.createSequentialGroup()
                                .addGroup(panelPolinomiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(textPrimitiva, javax.swing.GroupLayout.DEFAULT_SIZE, 444, Short.MAX_VALUE)
                                    .addComponent(textDerivada, javax.swing.GroupLayout.DEFAULT_SIZE, 444, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelPolinomiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(botoPujarPrimitiva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(botoPujarDerivada, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)))
                            .addComponent(textCoeficients, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 497, Short.MAX_VALUE)
                            .addComponent(textArrels, javax.swing.GroupLayout.DEFAULT_SIZE, 497, Short.MAX_VALUE)))
                    .addComponent(botoProcessarPolinomi, javax.swing.GroupLayout.DEFAULT_SIZE, 596, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelPolinomiLayout.setVerticalGroup(
            panelPolinomiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPolinomiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPolinomiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textCoeficients, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCoeficients))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelPolinomiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textArrels, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelArrels))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelPolinomiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botoPujarDerivada, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textDerivada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelDerivada))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelPolinomiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botoPujarPrimitiva, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textPrimitiva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelPrimitiva))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botoProcessarPolinomi)
                .addContainerGap(191, Short.MAX_VALUE))
        );

        panelPestanyes.addTab(resourceMap.getString("panelPolinomi.TabConstraints.tabTitle"), panelPolinomi); // NOI18N

        jPanel1.setName("jPanel1"); // NOI18N

        labelExtrem1.setText(resourceMap.getString("labelExtrem1.text")); // NOI18N
        labelExtrem1.setName("labelExtrem1"); // NOI18N

        labelExtrem2.setText(resourceMap.getString("labelExtrem2.text")); // NOI18N
        labelExtrem2.setName("labelExtrem2"); // NOI18N

        labelNombreDivisions.setText(resourceMap.getString("labelNombreDivisions.text")); // NOI18N
        labelNombreDivisions.setName("labelNombreDivisions"); // NOI18N

        textExtrem1.setText(resourceMap.getString("textExtrem1.text")); // NOI18N
        textExtrem1.setName("textExtrem1"); // NOI18N

        textExtrem2.setText(resourceMap.getString("textExtrem2.text")); // NOI18N
        textExtrem2.setName("textExtrem2"); // NOI18N

        textNombreParts.setText(resourceMap.getString("textNombreParts.text")); // NOI18N
        textNombreParts.setName("textNombreParts"); // NOI18N

        botoIntegrar.setText(resourceMap.getString("botoIntegrar.text")); // NOI18N
        botoIntegrar.setName("botoIntegrar"); // NOI18N
        botoIntegrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoIntegrarActionPerformed(evt);
            }
        });

        labelIntegral.setText(resourceMap.getString("labelIntegral.text")); // NOI18N
        labelIntegral.setName("labelIntegral"); // NOI18N

        textIntegral.setEditable(false);
        textIntegral.setText(resourceMap.getString("textIntegral.text")); // NOI18N
        textIntegral.setName("textIntegral"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelExtrem2)
                            .addComponent(labelExtrem1)
                            .addComponent(labelNombreDivisions)
                            .addComponent(labelIntegral))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textIntegral, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
                            .addComponent(textNombreParts, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
                            .addComponent(textExtrem2, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
                            .addComponent(textExtrem1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(botoIntegrar, javax.swing.GroupLayout.DEFAULT_SIZE, 596, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelExtrem1)
                    .addComponent(textExtrem1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelExtrem2)
                    .addComponent(textExtrem2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textNombreParts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNombreDivisions))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textIntegral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelIntegral))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botoIntegrar)
                .addContainerGap(209, Short.MAX_VALUE))
        );

        panelPestanyes.addTab(resourceMap.getString("jPanel1.TabConstraints.tabTitle"), jPanel1); // NOI18N

        jSplitPane1.setRightComponent(panelPestanyes);

        panelFuncions.setBorder(javax.swing.BorderFactory.createTitledBorder(resourceMap.getString("panelFuncions.border.title"))); // NOI18N
        panelFuncions.setName("panelFuncions"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        llistaFuncionsUsuari.setModel(new javax.swing.DefaultListModel());
        llistaFuncionsUsuari.setName("llistaFuncionsUsuari"); // NOI18N
        llistaFuncionsUsuari.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                llistaFuncionsUsuariMouseClicked(evt);
            }
        });
        llistaFuncionsUsuari.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                llistaFuncionsUsuariValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(llistaFuncionsUsuari);
        actualitzarLlistaFuncions();

        textFuncioUsuari.setText(resourceMap.getString("textFuncioUsuari.text")); // NOI18N
        textFuncioUsuari.setName("textFuncioUsuari"); // NOI18N
        textFuncioUsuari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFuncioUsuariActionPerformed(evt);
            }
        });
        textFuncioUsuari.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textFuncioUsuariFocusGained(evt);
            }
        });

        panelAfegirEsborrarFuncio.setName("panelAfegirEsborrarFuncio"); // NOI18N
        panelAfegirEsborrarFuncio.setLayout(new java.awt.GridLayout(1, 0));

        botoAfegirFuncioUsuari.setText(resourceMap.getString("botoAfegirFuncioUsuari.text")); // NOI18N
        botoAfegirFuncioUsuari.setToolTipText(resourceMap.getString("botoAfegirFuncioUsuari.toolTipText")); // NOI18N
        botoAfegirFuncioUsuari.setMaximumSize(new java.awt.Dimension(39, 23));
        botoAfegirFuncioUsuari.setMinimumSize(new java.awt.Dimension(39, 23));
        botoAfegirFuncioUsuari.setName("botoAfegirFuncioUsuari"); // NOI18N
        botoAfegirFuncioUsuari.setPreferredSize(new java.awt.Dimension(39, 23));
        botoAfegirFuncioUsuari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoAfegirFuncioUsuariActionPerformed(evt);
            }
        });
        panelAfegirEsborrarFuncio.add(botoAfegirFuncioUsuari);
        botoAfegirFuncioUsuari.getAccessibleContext().setAccessibleName(resourceMap.getString("botoAfegirFuncioUsuari.AccessibleContext.accessibleName")); // NOI18N

        botoEsborrarFuncioUsuari.setText(resourceMap.getString("botoEsborrarFuncioUsuari.text")); // NOI18N
        botoEsborrarFuncioUsuari.setToolTipText(resourceMap.getString("botoEsborrarFuncioUsuari.toolTipText")); // NOI18N
        botoEsborrarFuncioUsuari.setMaximumSize(new java.awt.Dimension(39, 23));
        botoEsborrarFuncioUsuari.setMinimumSize(new java.awt.Dimension(39, 23));
        botoEsborrarFuncioUsuari.setName("botoEsborrarFuncioUsuari"); // NOI18N
        botoEsborrarFuncioUsuari.setPreferredSize(new java.awt.Dimension(39, 23));
        botoEsborrarFuncioUsuari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoEsborrarFuncioUsuariActionPerformed(evt);
            }
        });
        panelAfegirEsborrarFuncio.add(botoEsborrarFuncioUsuari);
        botoEsborrarFuncioUsuari.getAccessibleContext().setAccessibleName(resourceMap.getString("botoEsborrarFuncioUsuari.AccessibleContext.accessibleName")); // NOI18N

        javax.swing.GroupLayout panelFuncionsLayout = new javax.swing.GroupLayout(panelFuncions);
        panelFuncions.setLayout(panelFuncionsLayout);
        panelFuncionsLayout.setHorizontalGroup(
            panelFuncionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelAfegirEsborrarFuncio, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
            .addComponent(textFuncioUsuari, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
        );
        panelFuncionsLayout.setVerticalGroup(
            panelFuncionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFuncionsLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFuncioUsuari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelAfegirEsborrarFuncio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jSplitPane1.setLeftComponent(panelFuncions);
        panelFuncions.getAccessibleContext().setAccessibleName(resourceMap.getString("jPanel1.AccessibleContext.accessibleName")); // NOI18N

        labelFzero.setFont(resourceMap.getFont("labelFzero.font")); // NOI18N
        labelFzero.setText(resourceMap.getString("labelFzero.text")); // NOI18N
        labelFzero.setName("labelFzero"); // NOI18N

        labelValorX.setText(resourceMap.getString("labelValorX.text")); // NOI18N
        labelValorX.setName("labelValorX"); // NOI18N

        textValorX.getDocument().addDocumentListener(new javax.swing.event.DocumentListener(){
            public void changedUpdate(javax.swing.event.DocumentEvent e){processarEntrada();}
            public void removeUpdate(javax.swing.event.DocumentEvent e){processarEntrada();}
            public void insertUpdate(javax.swing.event.DocumentEvent e){processarEntrada();}
        });
        textValorX.setFont(textValorX.getFont().deriveFont((float)18));
        textValorX.setText(resourceMap.getString("textValorX.text")); // NOI18N
        textValorX.setName("textValorX"); // NOI18N
        textValorX.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textValorXFocusGained(evt);
            }
        });

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelFx)
                            .addComponent(labelFzero))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textEntrada, javax.swing.GroupLayout.DEFAULT_SIZE, 656, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrincipalLayout.createSequentialGroup()
                                .addComponent(textResultat, javax.swing.GroupLayout.DEFAULT_SIZE, 528, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelValorX)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textValorX, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 725, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelFx))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(textResultat, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                        .addComponent(labelFzero))
                    .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(textValorX, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                        .addComponent(labelValorX)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE))
        );

        barraMenu.setName("barraMenu"); // NOI18N

        menuFitxer.setText(resourceMap.getString("menuFitxer.text")); // NOI18N
        menuFitxer.setName("menuFitxer"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(calcbatx.CalcBatxApp.class).getContext().getActionMap(CalcBatxView.class, this);
        tancarMenuItem.setAction(actionMap.get("quit")); // NOI18N
        tancarMenuItem.setText(resourceMap.getString("tancarMenuItem.text")); // NOI18N
        tancarMenuItem.setToolTipText(resourceMap.getString("tancarMenuItem.toolTipText")); // NOI18N
        tancarMenuItem.setName("tancarMenuItem"); // NOI18N
        menuFitxer.add(tancarMenuItem);

        barraMenu.add(menuFitxer);

        menuAjuda.setLabel(resourceMap.getString("menuAjuda.label")); // NOI18N
        menuAjuda.setName("menuAjuda"); // NOI18N

        ajudaMenuItem.setAction(actionMap.get("showAboutBox")); // NOI18N
        ajudaMenuItem.setText(resourceMap.getString("ajudaMenuItem.text")); // NOI18N
        ajudaMenuItem.setName("ajudaMenuItem"); // NOI18N
        menuAjuda.add(ajudaMenuItem);

        barraMenu.add(menuAjuda);

        barraEstat.setName("barraEstat"); // NOI18N

        statusPanelSeparator.setName("statusPanelSeparator"); // NOI18N

        labelEstat.setText(resourceMap.getString("labelEstat.text")); // NOI18N
        labelEstat.setName("labelEstat"); // NOI18N

        javax.swing.GroupLayout barraEstatLayout = new javax.swing.GroupLayout(barraEstat);
        barraEstat.setLayout(barraEstatLayout);
        barraEstatLayout.setHorizontalGroup(
            barraEstatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(statusPanelSeparator, javax.swing.GroupLayout.DEFAULT_SIZE, 749, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, barraEstatLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelEstat, javax.swing.GroupLayout.DEFAULT_SIZE, 725, Short.MAX_VALUE)
                .addContainerGap())
        );
        barraEstatLayout.setVerticalGroup(
            barraEstatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barraEstatLayout.createSequentialGroup()
                .addComponent(statusPanelSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelEstat)
                .addGap(9, 9, 9))
        );

        mostrarEstatCorrecte();

        menuGrafic.setName("menuGrafic"); // NOI18N

        menuMostrarRe.setText(resourceMap.getString("menuMostrarRe.text")); // NOI18N
        menuMostrarRe.setName("menuMostrarRe"); // NOI18N

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, panelGrafic, org.jdesktop.beansbinding.ELProperty.create("${mostrarRe}"), menuMostrarRe, org.jdesktop.beansbinding.BeanProperty.create("selected"));
        bindingGroup.addBinding(binding);

        menuGrafic.add(menuMostrarRe);

        menuMostrarIm.setText(resourceMap.getString("menuMostrarIm.text")); // NOI18N
        menuMostrarIm.setName("menuMostrarIm"); // NOI18N

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, panelGrafic, org.jdesktop.beansbinding.ELProperty.create("${mostrarIm}"), menuMostrarIm, org.jdesktop.beansbinding.BeanProperty.create("selected"));
        bindingGroup.addBinding(binding);

        menuGrafic.add(menuMostrarIm);

        setComponent(panelPrincipal);
        setMenuBar(barraMenu);
        setStatusBar(barraEstat);

        bindingGroup.bind();
    }// </editor-fold>//GEN-END:initComponents

    private void mostrarEstatCorrecte() {
        labelEstat.setText("Correcte.");
        labelEstat.setForeground(Color.BLUE);
    }

    private void mostrarEstatError(String msg) {
        labelEstat.setText("ERROR: " + msg);
        labelEstat.setForeground(Color.RED);
    }

    FuncioUsuari funcioResultat = null;
    Complex valorX = Complex.NaN;
    Complex resultat = Complex.NaN;

    private void processarEntrada() {
        funcioResultat = null;
        mostrarEstatCorrecte();

        try {
            funcioResultat = new ProcessadorExpressio("f(x)=" + textEntrada.getText()).processar();
        } catch (Exception exception) {
            mostrarEstatError(exception.getMessage());
        }

        try {
            valorX = new ProcessadorExpressio("x=" + textValorX.getText()).processar().calcular(null);
        } catch (Exception exception) {
            mostrarEstatError("No es pot calcular el valor d'x (" + exception.getMessage() + ")");
        }

        calcularResultat();
    }

    private void calcularResultat() {
        resultat = Complex.NaN;
        if (funcioResultat != null) {
            try {
                resultat = funcioResultat.calcular(new Complex[] { valorX });
            } catch (Exception exception) {
                mostrarEstatError(exception.getMessage());
            }
        }

        panelGrafic.setFuncio(funcioResultat);
        textResultat.setText(resultat.toString());
    }

    private void textFuncioUsuariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFuncioUsuariActionPerformed
        botoAfegirFuncioUsuari.doClick();
    }//GEN-LAST:event_textFuncioUsuariActionPerformed

    private void llistaFuncionsUsuariValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_llistaFuncionsUsuariValueChanged
        Funcio f = (Funcio)llistaFuncionsUsuari.getSelectedValue();

        if (f != null && f instanceof FuncioUsuari)
            textFuncioUsuari.setText(((FuncioUsuari)f).text);
        else
            textFuncioUsuari.setText("");
    }//GEN-LAST:event_llistaFuncionsUsuariValueChanged

    private void actualitzarLlistaFuncions() {
        DefaultListModel model = (DefaultListModel)llistaFuncionsUsuari.getModel();
        model.clear();
        for (Funcio f : Funcio.llista.values())
            model.addElement(f);
    }

    private void botoAfegirFuncioUsuariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoAfegirFuncioUsuariActionPerformed
        try {
            Funcio f = new ProcessadorExpressio(textFuncioUsuari.getText()).processar();
            Funcio.afegir(f);
        } catch (ProcessadorExpressioException exception) {
            mostrarEstatError(exception.getMessage());
        }

        actualitzarLlistaFuncions();
    }//GEN-LAST:event_botoAfegirFuncioUsuariActionPerformed

    private void botoEsborrarFuncioUsuariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoEsborrarFuncioUsuariActionPerformed
        for (Object f : llistaFuncionsUsuari.getSelectedValues())
            Funcio.llista.remove(((Funcio)f).nom);

        actualitzarLlistaFuncions();
    }//GEN-LAST:event_botoEsborrarFuncioUsuariActionPerformed

    private void afegirText(String s) {
        int posText = textSeleccionat.getCaretPosition();
        try {
            textSeleccionat.getDocument().insertString(posText, s, null);
        } catch (Exception e) { }
        textSeleccionat.requestFocus();
    }

    private void afegirTextFuncio(String nomFuncio) {
        afegirText(nomFuncio + "()");
        textSeleccionat.setCaretPosition(textSeleccionat.getCaretPosition() - 1);
    }

    private void llistaFuncionsUsuariMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_llistaFuncionsUsuariMouseClicked
        if (evt.getClickCount() == 2) {
            Funcio f = (Funcio)llistaFuncionsUsuari.getSelectedValue();
            if (f != null)
                afegirTextFuncio(f.nom);
        }
    }//GEN-LAST:event_llistaFuncionsUsuariMouseClicked

    private void botoIntegrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoIntegrarActionPerformed
        textIntegral.setText(Complex.NaN.toString());

        if (funcioResultat == null) {
            mostrarEstatError("No hi ha funció.");
            return;
        }

        try {
            double extrem1 = Double.parseDouble(textExtrem1.getText());
            double extrem2 = Double.parseDouble(textExtrem2.getText());
            int parts = Integer.parseInt(textNombreParts.getText());
            textIntegral.setText(Integral.calcular(funcioResultat, extrem1, extrem2, parts).toString());
        } catch (NumberFormatException exception) {
            mostrarEstatError("Les dades introduides per calcular la integral no són vàlides.");
        }
}//GEN-LAST:event_botoIntegrarActionPerformed

    private void botoPujarPrimitivaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoPujarPrimitivaActionPerformed
        textEntrada.setText(textPrimitiva.getText());
}//GEN-LAST:event_botoPujarPrimitivaActionPerformed

    private void botoPujarDerivadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoPujarDerivadaActionPerformed
        textEntrada.setText(textDerivada.getText());
}//GEN-LAST:event_botoPujarDerivadaActionPerformed

    private void botoProcessarPolinomiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoProcessarPolinomiActionPerformed
        textCoeficients.setText("");
        textArrels.setText("");
        textDerivada.setText("");
        textPrimitiva.setText("");

        if (funcioResultat == null) {
            mostrarEstatError("No hi ha funció.");
            return;
        }

        try {
            Polinomi p = new ProcessadorPolinomi(funcioResultat).processar();

            textCoeficients.setText(Arrays.toString(p.getCoeficients()));
            textArrels.setText(Arrays.toString(p.trobarArrels()));
            textDerivada.setText(p.derivada().toString());
            textPrimitiva.setText(p.primitiva().toString());
        } catch (ExpressioException exception) {
            mostrarEstatError(exception.getMessage());
        }
}//GEN-LAST:event_botoProcessarPolinomiActionPerformed

    private void botoSumarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoSumarActionPerformed
        afegirText("+");
}//GEN-LAST:event_botoSumarActionPerformed

    private void botoRestarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoRestarActionPerformed
        afegirText("-");
}//GEN-LAST:event_botoRestarActionPerformed

    private void botoMultiplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoMultiplicarActionPerformed
        afegirText("*");
}//GEN-LAST:event_botoMultiplicarActionPerformed

    private void botoDividirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoDividirActionPerformed
        afegirText("/");
}//GEN-LAST:event_botoDividirActionPerformed

    private void botoElevarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoElevarActionPerformed
        afegirText("^");
}//GEN-LAST:event_botoElevarActionPerformed

    private void botoExpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoExpActionPerformed
        afegirText("e");
}//GEN-LAST:event_botoExpActionPerformed

    private void botoPuntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoPuntActionPerformed
        afegirText(".");
}//GEN-LAST:event_botoPuntActionPerformed

    private void botoNombre0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoNombre0ActionPerformed
        afegirText("0");
}//GEN-LAST:event_botoNombre0ActionPerformed

    private void botoNombre3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoNombre3ActionPerformed
        afegirText("3");
}//GEN-LAST:event_botoNombre3ActionPerformed

    private void botoNombre2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoNombre2ActionPerformed
        afegirText("2");
}//GEN-LAST:event_botoNombre2ActionPerformed

    private void botoNombre1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoNombre1ActionPerformed
        afegirText("1");
}//GEN-LAST:event_botoNombre1ActionPerformed

    private void botoNombre6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoNombre6ActionPerformed
        afegirText("6");
}//GEN-LAST:event_botoNombre6ActionPerformed

    private void botoNombre5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoNombre5ActionPerformed
        afegirText("5");
}//GEN-LAST:event_botoNombre5ActionPerformed

    private void botoNombre4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoNombre4ActionPerformed
        afegirText("4");
}//GEN-LAST:event_botoNombre4ActionPerformed

    private void botoNombre9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoNombre9ActionPerformed
        afegirText("9");
}//GEN-LAST:event_botoNombre9ActionPerformed

    private void botoNombre8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoNombre8ActionPerformed
        afegirText("8");
}//GEN-LAST:event_botoNombre8ActionPerformed

    private void botoNombre7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoNombre7ActionPerformed
        afegirText("7");
}//GEN-LAST:event_botoNombre7ActionPerformed

    private void botoDerivadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoDerivadaActionPerformed
        afegirTextFuncio("D");
}//GEN-LAST:event_botoDerivadaActionPerformed

    private void botoTancarParentesisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoTancarParentesisActionPerformed
        afegirText(")");
}//GEN-LAST:event_botoTancarParentesisActionPerformed

    private void botoObrirParentesisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoObrirParentesisActionPerformed
        afegirText("(");
}//GEN-LAST:event_botoObrirParentesisActionPerformed

    private void botoValorIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoValorIActionPerformed
        afegirText("i");
}//GEN-LAST:event_botoValorIActionPerformed

    private void botoValorXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoValorXActionPerformed
        afegirText("x");
}//GEN-LAST:event_botoValorXActionPerformed

    private void botoReiniciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoReiniciaActionPerformed
        textSeleccionat.setText("");
}//GEN-LAST:event_botoReiniciaActionPerformed

    private void botoRetrocesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoRetrocesActionPerformed
        int posText = textSeleccionat.getCaretPosition();
        if (posText > 0) {
            try {
                textSeleccionat.getDocument().remove(posText - 1, 1);
            } catch (Exception e) { }
        }

        textSeleccionat.requestFocus();
}//GEN-LAST:event_botoRetrocesActionPerformed

    private void textEntradaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textEntradaFocusGained
        textSeleccionat = textEntrada;
    }//GEN-LAST:event_textEntradaFocusGained

    private void textValorXFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textValorXFocusGained
        textSeleccionat = textValorX;
    }//GEN-LAST:event_textValorXFocusGained

    private void textFuncioUsuariFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFuncioUsuariFocusGained
        textSeleccionat = textFuncioUsuari;
    }//GEN-LAST:event_textFuncioUsuariFocusGained

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ajudaMenuItem;
    private javax.swing.JPanel barraEstat;
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JButton botoAfegirFuncioUsuari;
    private javax.swing.JButton botoDerivada;
    private javax.swing.JButton botoDividir;
    private javax.swing.JButton botoElevar;
    private javax.swing.JButton botoEsborrarFuncioUsuari;
    private javax.swing.JButton botoExp;
    private javax.swing.JButton botoIntegrar;
    private javax.swing.JButton botoMultiplicar;
    private javax.swing.JButton botoNombre0;
    private javax.swing.JButton botoNombre1;
    private javax.swing.JButton botoNombre2;
    private javax.swing.JButton botoNombre3;
    private javax.swing.JButton botoNombre4;
    private javax.swing.JButton botoNombre5;
    private javax.swing.JButton botoNombre6;
    private javax.swing.JButton botoNombre7;
    private javax.swing.JButton botoNombre8;
    private javax.swing.JButton botoNombre9;
    private javax.swing.JButton botoObrirParentesis;
    private javax.swing.JButton botoProcessarPolinomi;
    private javax.swing.JButton botoPujarDerivada;
    private javax.swing.JButton botoPujarPrimitiva;
    private javax.swing.JButton botoPunt;
    private javax.swing.JButton botoReinicia;
    private javax.swing.JButton botoRestar;
    private javax.swing.JButton botoRetroces;
    private javax.swing.JButton botoSumar;
    private javax.swing.JButton botoTancarParentesis;
    private javax.swing.JButton botoValorI;
    private javax.swing.JButton botoValorX;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel labelArrels;
    private javax.swing.JLabel labelCoeficients;
    private javax.swing.JLabel labelDerivada;
    private javax.swing.JLabel labelEstat;
    private javax.swing.JLabel labelExtrem1;
    private javax.swing.JLabel labelExtrem2;
    private javax.swing.JLabel labelFx;
    private javax.swing.JLabel labelFzero;
    private javax.swing.JLabel labelIntegral;
    private javax.swing.JLabel labelNombreDivisions;
    private javax.swing.JLabel labelPrimitiva;
    private javax.swing.JLabel labelValorX;
    private javax.swing.JList llistaFuncionsUsuari;
    private javax.swing.JPopupMenu menuGrafic;
    private javax.swing.JCheckBoxMenuItem menuMostrarIm;
    private javax.swing.JCheckBoxMenuItem menuMostrarRe;
    private javax.swing.JPanel panelAfegirEsborrarFuncio;
    private javax.swing.JPanel panelFuncions;
    private calcbatx.GraficFuncio panelGrafic;
    private javax.swing.JTabbedPane panelPestanyes;
    private javax.swing.JPanel panelPolinomi;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JPanel panelTeclat;
    private javax.swing.JPanel panelTeclatControl;
    private javax.swing.JPanel panelTeclatControlValors;
    private javax.swing.JPanel panelTeclatDerivada;
    private javax.swing.JPanel panelTeclatNombres;
    private javax.swing.JPanel panelTeclatOperacions;
    private javax.swing.JPanel panelTeclatParentesis;
    private javax.swing.JPanel panelTeclatParentesisDerivada;
    private javax.swing.JPanel panelTeclatValors;
    private javax.swing.JTextField textArrels;
    private javax.swing.JTextField textCoeficients;
    private javax.swing.JTextField textDerivada;
    private javax.swing.JTextField textEntrada;
    private javax.swing.JTextField textExtrem1;
    private javax.swing.JTextField textExtrem2;
    private javax.swing.JTextField textFuncioUsuari;
    private javax.swing.JTextField textIntegral;
    private javax.swing.JTextField textNombreParts;
    private javax.swing.JTextField textPrimitiva;
    private javax.swing.JTextField textResultat;
    private javax.swing.JTextField textValorX;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

    javax.swing.JTextField textSeleccionat = textEntrada;
}
